version: 2
updates:
  - package-ecosystem: npm
    directory: '/packages/ts-dev-stack'
    schedule:
      interval: daily
    ignore:
      - dependency-name: '@swc/core'
      - dependency-name: 'assert'
      - dependency-name: 'lodash.camelcase'
      - dependency-name: 'mkdirp'
      - dependency-name: 'pirates'
      - dependency-name: 'rimraf'
      - dependency-name: 'rollup'
      - dependency-name: 'rollup-plugin-node-externals'
      - dependency-name: 'ts-node'
      - dependency-name: 'regenerator-runtime'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
